ALTER TABLE appSettings ADD COLUMN apiEnabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE appSettings ADD COLUMN apiPort INTEGER NOT NULL DEFAULT 3100;
ALTER TABLE appSettings ADD COLUMN apiHost TEXT NOT NULL DEFAULT '127.0.0.1';
